#ifndef TSQTPLATFORM_GLOBAL_H
#define TSQTPLATFORM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TSQTPLATFORM_LIBRARY)
#  define TSQTPLATFORMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TSQTPLATFORMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TSQTPLATFORM_GLOBAL_H
